-- Populate language-specific translations for the current tours so the public site
-- reflects the selected language instead of falling back to the default English tour data.

INSERT INTO tour_translations (tour_id, language, title, slug, short_description, description, duration)
VALUES
    (1, 'de', 'Safari Blue Zanzibar', 'safari-blue-zanzibar', 'Ein ganztägiges Abenteuer auf See mit Dhow-Segeln, Schnorcheln und Sandbank-Erlebnissen.', 'Erlebe einen unvergesslichen Tag auf den Gewässern rund um Zanzibar mit traditioneller Dhow-Segeln, Schnorcheln, Sandbank-Erlebnissen und einem köstlichen Inselmittagessen.', 'Ganzer Tag'),
    (1, 'fr', 'Safari Blue Zanzibar', 'safari-blue-zanzibar', 'Une aventure marine d''une journée avec navigation en dhow, snorkeling et expérience de banc de sable.', 'Profitez d''une journée mémorable en explorant les eaux autour de Zanzibar avec une navigation traditionnelle en dhow, du snorkeling, des expériences sur banc de sable et un délicieux déjeuner à l''inspiration insulaire.', 'Journée complète'),
    (1, 'it', 'Safari Blue Zanzibar', 'safari-blue-zanzibar', 'Un''avventura marina di una giornata con vela in dhow, snorkeling e esperienza sulla spiaggia sabbiosa.', 'Goditi una giornata indimenticabile esplorando le acque intorno a Zanzibar con navigazione tradizionale in dhow, snorkeling, esperienze sulla spiaggia sabbiosa e un delizioso pranzo tipico dell''isola.', 'Giornata intera'),
    (1, 'pl', 'Safari Blue Zanzibar', 'safari-blue-zanzibar', 'Pełnodniowa przygoda morska z żeglugą na dhow, nurkowaniem i doświadczeniem na piaszczystym łasze.', 'Spędź niezapomniany dzień, odkrywając wody wokół Zanzibar z tradycyjnym żeglowaniem na dhow, nurkowaniem, doświadczeniami na piaszczystym łasze i pysznym obiadem w stylu wyspiarskim.', 'Cały dzień'),

    (2, 'de', 'Mnemba Island Delfin- & Schnorchelabenteuer', 'mnemba-island-delfin-schnorchel-abenteuer', 'Erlebe die kristallklaren Gewässer Sansibars mit Delfinbeobachtung, tropischem Schnorcheln und atemberaubender Küstenlandschaft.', 'Erlebe die Schönheit der Nordküste Sansibars bei einem unvergesslichen Mnemba Island Delfin- & Schnorchelabenteuer. Beginne deine Reise mit einer malerischen Bootsfahrt über das türkisfarbene Wasser des Indischen Ozeans, während du eine der spektakulärsten Meeresumgebungen Sansibars erkundest. Tauche in klares tropisches Wasser ein und entdecke farbenfrohe Korallenriffe, tropische Fische und faszinierende Meereslebewesen.', 'Ganzer Tag'),
    (2, 'fr', 'Aventure dauphins et snorkeling à l''île Mnemba', 'aventure-dauphins-snorkeling-ile-mnemba', 'Découvrez les eaux cristallines de Zanzibar avec observation de dauphins, snorkeling tropical et paysages marins époustouflants.', 'Découvrez la beauté de la côte nord de Zanzibar lors d''une aventure inoubliable à l''île Mnemba. Commencez avec une balade en bateau sur les eaux turquoise de l''océan Indien avant d''explorer l''un des environnements marins les plus spectaculaires de Zanzibar.', 'Journée complète'),
    (2, 'it', 'Avventura con delfini e snorkeling all''isola di Mnemba', 'avventura-con-delfini-e-snorkeling-all-isola-di-mnemba', 'Scopri le acque cristalline di Zanzibar con avvistamento di delfini, snorkeling tropicale e paesaggi marini mozzafiato.', 'Scopri la bellezza della costa settentrionale di Zanzibar in un''avventura indimenticabile all''isola di Mnemba. Inizia con un giro in barca sulle acque turchesi dell''Oceano Indiano prima di esplorare uno dei paesaggi marini più spettacolari di Zanzibar.', 'Giornata intera'),
    (2, 'pl', 'Przygoda z delfinami i nurkowaniem na wyspie Mnemba', 'przygoda-z-delfinami-i-nurkowaniem-na-wyspie-mnemba', 'Odkryj krystalicznie czyste wody Zanzibar z obserwacją delfinów, tropikalnym nurkowaniem i zapierającymi dech widokami.', 'Odkryj piękno północnego wybrzeża Zanzibar podczas niezapomnianej przygody na wyspie Mnemba. Zacznij od przejażdżki łodzią po turkusowych wodach Oceanu Indyjskiego, zanim odkryjesz jedno z najbardziej spektakularnych środowisk morskich Zanzibar.', 'Cały dzień'),

    (3, 'de', 'Nungwi Strand & Luxusauto-Erlebnis', 'nungwi-strand-luxusauto-erlebnis', 'Erlebe die lebendige Schönheit von Nungwi mit einem einzigartigen Strandabenteuer und einem luxuriösen Autoerlebnis.', 'Entdecke die Schönheit und die lebendige Atmosphäre von Nungwi, einem der beliebtesten Küstenziele Sansibars. Genieße den spektakulären weißen Sandstrand, die türkisfarbenen Gewässer und die tropische Atmosphäre, die Nungwi zu einem Lieblingsziel machen.', 'Halber Tag'),
    (3, 'fr', 'Plage de Nungwi et expérience de voiture de luxe', 'plage-de-nungwi-experience-voiture-de-luxe', 'Découvrez la beauté vibrante de Nungwi avec une aventure unique sur la plage et une expérience de voiture de luxe.', 'Découvrez la beauté et l''atmosphère animée de Nungwi, l''une des destinations côtières les plus populaires de Zanzibar. Profitez d''une plage de sable blanc spectaculaire, d''eaux turquoise, de palmiers tropicaux et de l''ambiance dynamique qui fait de Nungwi un lieu privilégié.', 'Demi-journée'),
    (3, 'it', 'Spiaggia di Nungwi ed esperienza con auto di lusso', 'spiaggia-di-nungwi-ed-esperienza-con-auto-di-lusso', 'Scopri la vibrante bellezza di Nungwi con un''avventura unica sulla spiaggia e un''esperienza con auto di lusso.', 'Scopri la bellezza e l''atmosfera vivace di Nungwi, una delle destinazioni costiere più popolari di Zanzibar. Goditi la spettacolare spiaggia di sabbia bianca, le acque turchesi, le palme tropicali e l''ambiente vivace che rende Nungwi una meta amata dai visitatori.', 'Mezza giornata'),
    (3, 'pl', 'Plaża Nungwi i luksusowe doświadczenie samochodem', 'plaza-nungwi-i-luksusowe-doswiadczenie-samochodem', 'Odkryj żywe piękno Nungwi z unikalną przygodą na plaży i luksusowym doświadczeniem samochodowym.', 'Odkryj piękno i żywą atmosferę Nungwi, jednego z najpopularniejszych miejsc nadmorskich Zanzibar. Ciesz się spektakularną białą plażą, turkusowymi wodami, tropikalnymi palmami i żywą atmosferą, która sprawia, że Nungwi jest ulubionym miejscem odwiedzających.', 'Pół dnia')
ON CONFLICT (tour_id, language) DO UPDATE
SET
    title = EXCLUDED.title,
    slug = EXCLUDED.slug,
    short_description = EXCLUDED.short_description,
    description = EXCLUDED.description,
    duration = EXCLUDED.duration,
    updated_at = CURRENT_TIMESTAMP;
